"""Repository interfaces for the attendance module (incl. analytics)."""

import uuid
from datetime import date
from typing import Protocol

from app.modules.attendance.infrastructure.persistence.models import (
    AttendanceRecord,
    ServiceSession,
)


class ServiceSessionRepository(Protocol):
    async def get_by_id(self, session_id: uuid.UUID) -> ServiceSession | None: ...

    async def list_active(self) -> list[ServiceSession]: ...

    async def add(self, session: ServiceSession) -> None: ...


class AttendanceRepository(Protocol):
    async def add(self, record: AttendanceRecord) -> None: ...

    async def get_for_user_session(
        self, user_id: uuid.UUID, session_id: uuid.UUID
    ) -> AttendanceRecord | None: ...

    async def count_between(self, start: date, end: date) -> int: ...

    async def count_today(self) -> int: ...

    async def count_this_week(self, today: date) -> int: ...

    async def count_this_month(self, today: date) -> int: ...

    async def count_total(self) -> int: ...

    async def attendance_percentage_between(self, start: date, end: date) -> float | None: ...

    async def absent_users_since(self, cutoff: date) -> list[uuid.UUID]: ...

    async def daily_trend(self, start: date, end: date) -> list[tuple[date, int]]: ...

    async def list_between(self, start: date, end: date) -> list[AttendanceRecord]: ...
