"""Repository interfaces for the attendance module (incl. analytics)."""

import uuid
from datetime import date
from typing import Protocol

from app.modules.attendance.domain.entities import Attendance
from app.modules.attendance.domain.enums import AttendanceStatus
from app.modules.attendance.infrastructure.persistence.models import (
    AttendanceRecord,
    ServiceSession,
)


class ServiceSessionRepository(Protocol):
    async def get_by_id(self, session_id: uuid.UUID) -> ServiceSession | None: ...

    async def list_active(self) -> list[ServiceSession]: ...

    async def add(self, session: ServiceSession) -> None: ...


class AttendanceRepository(Protocol):
    """Service-session attendance plus meeting-level analytics."""

    async def add(self, record: AttendanceRecord) -> None: ...

    async def get_for_user_session(
        self, user_id: uuid.UUID, session_id: uuid.UUID
    ) -> AttendanceRecord | None: ...

    async def count_between(self, start: date, end: date) -> int: ...

    async def count_for_meeting(self, meeting_date: date) -> int: ...

    async def count_current_meeting(self, today: date | None = None) -> int: ...

    async def count_for_meetings(self, meetings: list[date]) -> int: ...

    async def count_month_meetings(self, today: date | None = None) -> int: ...

    async def count_total(self) -> int: ...

    async def attendance_percentage_between(self, start: date, end: date) -> float | None: ...

    async def absent_users_since(self, cutoff: date) -> list[uuid.UUID]: ...

    async def meeting_trend(self, start: date, end: date) -> list[tuple[date, int]]: ...

    async def list_between(self, start: date, end: date) -> list[AttendanceRecord]: ...


class WeeklyAttendanceRepository(Protocol):
    """QR check-in records, one per user per weekly meeting."""

    async def add(self, attendance: Attendance) -> Attendance: ...

    async def get_by_id(self, attendance_id: uuid.UUID) -> Attendance | None: ...

    async def find_by_user_and_meeting(
        self, user_id: uuid.UUID, meeting_date: date
    ) -> Attendance | None: ...

    async def find_by_meeting(self, meeting_date: date) -> list[Attendance]: ...

    async def find_by_meeting_range(self, start_date: date, end_date: date) -> list[Attendance]: ...

    async def find_by_user(self, user_id: uuid.UUID) -> list[Attendance]: ...

    async def count_by_meeting(self, meeting_date: date) -> int: ...

    async def count_by_meeting_and_status(
        self, meeting_date: date, status: AttendanceStatus
    ) -> int: ...

    async def counts_by_meeting(self, start_date: date, end_date: date) -> dict[date, int]: ...

    async def count_by_user_between(
        self, user_id: uuid.UUID, start_date: date, end_date: date
    ) -> int: ...

    async def count_distinct_attendees_between(self, start_date: date, end_date: date) -> int: ...

    async def counts_by_user_between(
        self, start_date: date, end_date: date
    ) -> dict[uuid.UUID, int]: ...
